version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: genially

  api:
    build: .
    container_name: genially-api
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - USE_MONGO_DB=true
      - MONGO_URI=mongodb://mongodb:27017/genially
